-- Based on the definitions within Code/Command/dialogresource.cpp/h

--- @class Renegade
local CNC = CNC_RENEGADE

--- @class DialogResourceClass
local STATIC = CNC.CreateExport()
STATIC.Class = "DialogResourceClass"
local isHotload = not table.IsEmpty( STATIC )

-- "
-- These button IDs are used for "simple" buttons
-- that's only purpose is to start a new dialog.
--
-- Note:  These IDs are coded using defines instead of an enumeration
-- because the resource compiler ignores enumerations.
-- "

STATIC.DIALOG_LINK_FIRST = 11000

STATIC.IDC_MENU_START_SP_GAME_BUTTON	= STATIC.DIALOG_LINK_FIRST
STATIC.IDC_MENU_START_MP_GAME_BUTTON	= STATIC.IDC_MENU_START_SP_GAME_BUTTON   + 1
STATIC.IDC_MENU_VIEW_SCORES_BUTTON		= STATIC.IDC_MENU_START_MP_GAME_BUTTON   + 1
STATIC.IDC_MENU_OPTIONS_BUTTON		    = STATIC.IDC_MENU_VIEW_SCORES_BUTTON     + 1
STATIC.IDC_MENU_START_CAMPAIGN_BUTTON   = STATIC.IDC_MENU_OPTIONS_BUTTON         + 1
STATIC.IDC_MENU_START_TUTORIAL_BUTTON	= STATIC.IDC_MENU_START_CAMPAIGN_BUTTON  + 1
STATIC.IDC_MENU_LOAD_SP_GAME_BUTTON		= STATIC.IDC_MENU_START_TUTORIAL_BUTTON  + 1
STATIC.IDC_MENU_DIFFCULTY01_BUTTON		= STATIC.IDC_MENU_LOAD_SP_GAME_BUTTON    + 1
STATIC.IDC_MENU_DIFFCULTY02_BUTTON		= STATIC.IDC_MENU_DIFFCULTY01_BUTTON     + 1
STATIC.IDC_MENU_DIFFCULTY03_BUTTON		= STATIC.IDC_MENU_DIFFCULTY02_BUTTON     + 1
STATIC.IDC_MENU_DIFFCULTY04_BUTTON		= STATIC.IDC_MENU_DIFFCULTY03_BUTTON     + 1
STATIC.IDC_MENU_CONTROLS_BUTTON		    = STATIC.IDC_MENU_DIFFCULTY04_BUTTON     + 1
STATIC.IDC_MENU_CHARACTER_BUTTON		= STATIC.IDC_MENU_CONTROLS_BUTTON        + 1
STATIC.IDC_MENU_CHEATS_BUTTON		    = STATIC.IDC_MENU_CHARACTER_BUTTON       + 1
STATIC.IDC_MENU_TECH_BUTTON		        = STATIC.IDC_MENU_CHEATS_BUTTON          + 1
STATIC.IDC_MENU_MOVIES_BUTTON		    = STATIC.IDC_MENU_TECH_BUTTON            + 1
STATIC.IDC_MENU_PREVIEWS_BUTTON		    = STATIC.IDC_MENU_MOVIES_BUTTON          + 1
STATIC.IDC_MENU_CREDITS_BUTTON		    = STATIC.IDC_MENU_PREVIEWS_BUTTON        + 1
STATIC.IDC_MENU_QUIT_BUTTON		        = STATIC.IDC_MENU_CREDITS_BUTTON         + 1
STATIC.IDC_MENU_INGAME_MENU_BUTTON		= STATIC.IDC_MENU_QUIT_BUTTON            + 1
STATIC.IDC_MENU_MAIN_MENU_BUTTON		= STATIC.IDC_MENU_INGAME_MENU_BUTTON     + 1
STATIC.IDC_MENU_SAVE_SP_GAME_BUTTON		= STATIC.IDC_MENU_MAIN_MENU_BUTTON       + 1
STATIC.IDC_MENU_MP_LAN_BUTTON		    = STATIC.IDC_MENU_SAVE_SP_GAME_BUTTON    + 1
STATIC.IDC_MENU_MP_INTERNET_BUTTON		= STATIC.IDC_MENU_MP_LAN_BUTTON          + 1
STATIC.IDC_MENU_MP_START_SERVER_BUTTON	= STATIC.IDC_MENU_MP_INTERNET_BUTTON     + 1
STATIC.IDC_MENU_MP_JOIN_GAME_BUTTON		= STATIC.IDC_MENU_MP_START_SERVER_BUTTON + 1
STATIC.IDC_MENU_MP_START_GAME_BUTTON	= STATIC.IDC_MENU_MP_JOIN_GAME_BUTTON    + 1

STATIC.IDC_MENU_MULTIPLAY_OPTS_BUTTON	= STATIC.IDC_MENU_MP_START_GAME_BUTTON + 1

STATIC.IDC_MENU_MP_MENU_BUTTON		    = STATIC.IDC_MENU_MULTIPLAY_OPTS_BUTTON   + 1
STATIC.IDC_MENU_MP_INTERNET_GAME_BUTTON	= STATIC.IDC_MENU_MP_MENU_BUTTON          + 1
STATIC.IDC_MENU_MP_LAN_GAME_BUTTON		= STATIC.IDC_MENU_MP_INTERNET_GAME_BUTTON + 1
STATIC.IDC_MENU_MP_LAN_JOIN_BUTTON		= STATIC.IDC_MENU_MP_LAN_GAME_BUTTON      + 1
STATIC.IDC_MENU_MP_LAN_START_BUTTON		= STATIC.IDC_MENU_MP_LAN_JOIN_BUTTON      + 1

STATIC.DIALOG_LINK_LAST		            = STATIC.IDC_MENU_MP_LAN_START_BUTTON + 1

-- "These IDs are for non-link controls that reside inside a dialog."
STATIC.IDC_MENU_BACK_BUTTON		     = STATIC.DIALOG_LINK_LAST            + 1
STATIC.IDC_LOAD_GAME_LIST_CTRL		 = STATIC.IDC_MENU_BACK_BUTTON        + 1
STATIC.IDC_DELETE_GAME_BUTTON		 = STATIC.IDC_LOAD_GAME_LIST_CTRL     + 1
STATIC.IDC_LOAD_GAME_BUTTON		     = STATIC.IDC_DELETE_GAME_BUTTON      + 1
STATIC.IDC_MENU_MP_START_BUTTON		 = STATIC.IDC_LOAD_GAME_BUTTON        + 1
STATIC.IDC_MENU_MP_JOING_BUTTON		 = STATIC.IDC_MENU_MP_START_BUTTON    + 1
STATIC.IDC_MP_NICKNAME_EDIT		     = STATIC.IDC_LOAD_GAME_BUTTON        + 1
STATIC.IDC_MP_CONNECTING_OK_BUTTON	 = STATIC.IDC_MP_NICKNAME_EDIT        + 1
STATIC.IDC_MP_PASSWORD_VALID_COMMAND = STATIC.IDC_MP_CONNECTING_OK_BUTTON + 1

STATIC.IDC_MP_SHORTCUT_NEWS		          = STATIC.IDC_MP_PASSWORD_VALID_COMMAND      + 1
STATIC.IDC_MP_SHORTCUT_CLANS		      = STATIC.IDC_MP_SHORTCUT_NEWS               + 1
STATIC.IDC_MP_SHORTCUT_RANKINGS		      = STATIC.IDC_MP_SHORTCUT_CLANS              + 1
STATIC.IDC_MP_SHORTCUT_BUDDIES		      = STATIC.IDC_MP_SHORTCUT_RANKINGS           + 1
STATIC.IDC_MP_SHORTCUT_ACCOUNT		      = STATIC.IDC_MP_SHORTCUT_BUDDIES            + 1
STATIC.IDC_MP_SHORTCUT_NET_STATUS		  = STATIC.IDC_MP_SHORTCUT_ACCOUNT            + 1
STATIC.IDC_MP_SHORTCUT_PAGE_BUDDY		  = STATIC.IDC_MP_SHORTCUT_NET_STATUS         + 1
STATIC.IDC_MP_SHORTCUT_CHAT               = STATIC.IDC_MP_SHORTCUT_PAGE_BUDDY         + 1
STATIC.IDC_MP_SHORTCUT_GAMELIST           = STATIC.IDC_MP_SHORTCUT_CHAT               + 1
STATIC.IDC_MP_SHORTCUT_QUICKMATCH_OPTIONS = STATIC.IDC_MP_SHORTCUT_GAMELIST           + 1
STATIC.IDC_MP_SHORTCUT_INTERNET_OPTIONS   = STATIC.IDC_MP_SHORTCUT_QUICKMATCH_OPTIONS + 1
STATIC.IDC_MENU_MP_LAN_HOST_BUTTON        = STATIC.IDC_MP_SHORTCUT_INTERNET_OPTIONS   + 1

STATIC.IDC_CNC_PURCHASE_VEHICLE_BUTTON   = 12000
STATIC.IDC_CNC_PURCHASE_POWERUP_BUTTON   = 12001
STATIC.IDC_CNC_PURCHASE_CHARACTER_BUTTON = 12002

STATIC.IDC_BUY_GDI_VEHICLE01_BUTTON = 2000
STATIC.IDC_BUY_GDI_VEHICLE02_BUTTON = 2001
STATIC.IDC_BUY_GDI_VEHICLE03_BUTTON = 2002
STATIC.IDC_BUY_GDI_VEHICLE04_BUTTON = 2003
STATIC.IDC_BUY_NOD_VEHICLE01_BUTTON = 2004
STATIC.IDC_BUY_NOD_VEHICLE02_BUTTON = 2005
STATIC.IDC_BUY_NOD_VEHICLE03_BUTTON = 2006
STATIC.IDC_BUY_NOD_VEHICLE04_BUTTON = 2007
STATIC.IDC_BUY_NOD_VEHICLE05_BUTTON = 2008
STATIC.IDC_BUY_NOD_VEHICLE06_BUTTON = 2009
STATIC.IDC_BUY_NOD_VEHICLE07_BUTTON = 2010

STATIC.IDC_BUY_POWERUP01_BUTTON = 3000
STATIC.IDC_BUY_POWERUP02_BUTTON = 3001
STATIC.IDC_BUY_POWERUP03_BUTTON = 3002
STATIC.IDC_BUY_POWERUP04_BUTTON = 3003
STATIC.IDC_BUY_POWERUP05_BUTTON = 3004
STATIC.IDC_BUY_POWERUP06_BUTTON = 3005
STATIC.IDC_BUY_POWERUP07_BUTTON = 3006
STATIC.IDC_BUY_POWERUP08_BUTTON = 3007
STATIC.IDC_BUY_POWERUP09_BUTTON = 3008
STATIC.IDC_BUY_POWERUP10_BUTTON = 3009
STATIC.IDC_BUY_POWERUP11_BUTTON = 3010
STATIC.IDC_BUY_POWERUP12_BUTTON = 3011
STATIC.IDC_BUY_POWERUP13_BUTTON = 3012
STATIC.IDC_BUY_POWERUP14_BUTTON = 3013

STATIC.IDC_BUY_CHARACTER01_BUTTON = 4000
STATIC.IDC_BUY_CHARACTER02_BUTTON = 4001
STATIC.IDC_BUY_CHARACTER03_BUTTON = 4002
STATIC.IDC_BUY_CHARACTER04_BUTTON = 4003
STATIC.IDC_BUY_CHARACTER05_BUTTON = 4004
STATIC.IDC_BUY_CHARACTER06_BUTTON = 4005
STATIC.IDC_BUY_CHARACTER07_BUTTON = 4006
STATIC.IDC_BUY_CHARACTER08_BUTTON = 4007
STATIC.IDC_BUY_CHARACTER09_BUTTON = 4008
STATIC.IDC_BUY_CHARACTER10_BUTTON = 4009
STATIC.IDC_BUY_CHARACTER11_BUTTON = 4010
STATIC.IDC_BUY_CHARACTER12_BUTTON = 4011
STATIC.IDC_BUY_CHARACTER13_BUTTON = 4012

STATIC.IDC_SCORE_TABCTRL   = 40001
STATIC.IDC_GENERIC_TABCTRL = 40002